# Generated by Django 4.0.1 on 2022-01-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descriptoins',
            new_name='descriptions',
        ),
    ]
