# Generated by Django 4.0.1 on 2022-02-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
