# Generated by Django 4.0.1 on 2022-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articlehit_article_hits_articlehit_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
